<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="GalleryData.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GalleryData.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="GalleryData.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>GalleryData.Designer.cs</LastGenOutput>
    </None>
    <None Update="RaportFormularz.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="RaportGrupowanie.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="RaportKlienta.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="RaportWykres.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>